cmake_minimum_required(VERSION 3.22.1)
project(codedb)
set(CMAKE_CXX_STANDARD 17)
add_library(node SHARED IMPORTED)
set(NODE_ROOT "${CMAKE_CURRENT_SOURCE_DIR}/../../../../.cache/node")
set_target_properties(node PROPERTIES IMPORTED_LOCATION "${NODE_ROOT}/bin/${ANDROID_ABI}/libnode.so")
add_library(codedb SHARED runtime.cpp)
target_include_directories(codedb PRIVATE "${NODE_ROOT}/include/node")
target_link_libraries(codedb node log)
